# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abf72ab7f4a6b15b8975e4cd263577678b36cc3d35be22b1bdc57548b53837582e9af43f90480ab00489f90d0123c1d148aba9a32ca797ae6b72fc52e9ae4320

test:
  secret_key_base: 4b202c0aeb87997becd3bb3a69c4bb8ba4bcb77754eed700d31839e80a56b845bdb8b0be833586d64c9b29a6a706302172fd31bc44bc951dc47d6d9c5a308578

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
